### ISSUE TITLE
[BUG] "Details"

### ISSUE THREAD

**Issue by Srsbsns69** [Althro/Tinvaak2#10]
**Upload your crashlog**

N/A - No crash.

**Required: Modlist.txt**
[modlist.txt](https://github.com/Althro/Tinvaak2/files/7534250/modlist.txt)

You must also include your modlist.txt from `F:\Tinvaak\profiles\Tinvaak`

**Describe the bug**
Dodge does not work in first person. Also, in third person, it always does a slide when moving (always detects that you're moving forward, not that you're strafing or moving backwards as it should respectively). I believe this is an issue with either the TDM patch for engarde or nemesis patch.

**To Reproduce**

Use dodge (defensive action in Engarde) either in first person (animation / movement doesn't work) or third person while moving (you will slide dodge instead of sidestep.)

If you turn off TDM via MCM you will see that the dodge will sort of work correctly in third person (sidestep instead of slide) but it's still not 100% what engarde dodge should be.

**Expected behavior**
Dodging should work in first person. Dodging should work in third person with the slide only occurring if you're moving forward, not side to side or backwards. In these cases it should be a sidestep.

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

**Modlist version**
V2.1

**Did you add any additional mods?**

Nope. I did a complete delete and reinstall for testing, thinking that having updated from the last version might have caused it. Unfortunately, the issue still exists.

***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***

**Comment by Althro** [comment]
There is not a lot I can do about this sadly. I'm already using the TDM patch for Nemesis and Engarde.

**Comment by Althro** [comment]
I was also just informed by the team that you have in fact modified the list. You have thus voided any support.

**Comment by Srsbsns69** [comment]
Hey Althro, I had improved camera installed on an earlier version. I did a complete uninstall / reinstall for testing purposes. I have modified the list previously however, and if doing that at any point in the past means you don't want any bug reports or issue notifications going forward (even if they're from a clean and unmodified list), that's fine.

**Comment by Srsbsns69** [comment]
Hey, sorry for using this channel but I'm not sure how else to ask, why was I removed from the discord overnight?
