### ISSUE TITLE
Issue with downloading 2 mods on Wabbajack

### ISSUE THREAD

**Issue by rperezandreiuk** [Althro/Tinvaak2#11]
Hello, friends.

I am kind of a noobie in computing, so, I hope my problem is easy enough to fix. :-)
Everything worked out nicely during the download, except for two files:
1. T2LandscapeResources.7z
2. enbseries_skyrimse_v0463.zip
I tried looking for them, but I could not find neither.
Could someone point me on the correct direction on fixing the situation? 
Thanks in advance!!!
Best regards;-)

**Comment by Althro** [comment]
Please check in the wabbajack discord server for these files. The former is pinned in the support channel and the latter should be downloadable if you use a VPN or select network workaround.
