### ISSUE TITLE
[BUG] does not start

### ISSUE THREAD

**Issue by 85thOperationCommand** [Althro/Tinvaak2#12]
**Upload your crashlog**

No Crash log i have only from Wabbajack: [Wabbajack 2021-12-15 00_14_05.log](https://github.com/Althro/Tinvaak2/files/7715367/Wabbajack.2021-12-15.00_14_05.log)

**Required: Modlist.txt**
[modlist.txt](https://github.com/Althro/Tinvaak2/files/7715371/modlist.txt)

**Describe the bug**
I have the problem that skyrim does not start after installing the modpack - the CMD only appears briefly. I followed the instructions. In the download folder I have 1367 files of which 90 are META files. every time I go over it with Wabbajack, 90 mods are installed and they are always the same. I also deleted them and downloaded them again.

**To Reproduce**
just install

**Expected behavior**
Skyrim starts

**Modlist version**
2.1

**Did you add any additional mods?**
no

**Comment by Althro** [comment]
Follow the readme in full and make sure you have installed .net framework. Your WJ log tells me that the list has installed fine.
