### ISSUE TITLE
[Installation issue] T2LandscapeResources.7z

### ISSUE THREAD

**Issue by wongocat** [Althro/Tinvaak2#13]
I have been attempting to get this last mod downloaded it always fails. any assistance would be more than appreciated.

[Wabbajack.current.log](https://github.com/Althro/Tinvaak2/files/7774749/Wabbajack.current.log)

**Comment by wongocat** [comment]
@Althro

**Comment by Althro** [comment]
Please join the discord server which can be accessed via the wabbajack server for a mirror to the files.
