### ISSUE TITLE
[BUG] "ScrollScribe crafting menu is empty"

### ISSUE THREAD

**Issue by paulogrupp** [Althro/Tinvaak2#14]
[modlist.txt](https://github.com/Althro/Tinvaak2/files/7774993/modlist.txt)

**Describe the bug**
The scroll crafting menu from scrollscribe is always empty

**To Reproduce**

1. Activate a scroll crafting station (at the college of Winterhold, for example).
2. Or use the scroll crafting spell

**Expected behavior**
The scroll crafting menu should display scrolls to be crafted depending on the Inscription knowledge of the character.

**Modlist version**
2.1
**Did you add any additional mods?**
No

**Comment by Althro** [comment]
Ensure that you do know spells before attempting to craft them. If you do not know a spell, then it won't be able to be crafted.

**Comment by paulogrupp** [comment]
I just created a character with Conjure Familiar, Reanimate lesser corpse and flames. I also added rolls of paper, soul gems and arcane dust via console command, but the menu is still empty. I tried to follow [this demonstration](https://www.youtube.com/watch?v=3uIrRwwR40g) , but I can't get the menu with the "disabled" scrolls.

**Comment by Para0x** [comment]
Apologies for the delay in the response. We have found the solution and it will be resolved with the upcoming update. Still no ETA as to when we'll drop that, though.

We appreciate your patience!

**Comment by Althro** [comment]
Fixed in version 2.3 (coming soon)
