### ISSUE TITLE
[BUG] Random crashes while fast traveling after guar fix applied

### ISSUE THREAD

**Issue by chilblane** [Althro/Tinvaak2#19]
**Upload your crashlog**

[Crash_2022_1_9_11-7-7.txt](https://github.com/Althro/Tinvaak2/files/7858430/Crash_2022_1_9_11-7-7.txt)
[Crash_2022_1_9_18-35-19.txt](https://github.com/Althro/Tinvaak2/files/7858433/Crash_2022_1_9_18-35-19.txt)
[Crash_2022_1_12_15-13-0.txt](https://github.com/Althro/Tinvaak2/files/7858434/Crash_2022_1_12_15-13-0.txt)

**Required: Modlist.txt**

[modlist.txt](https://github.com/Althro/Tinvaak2/files/7858440/modlist.txt)

**Describe the bug**
After applying the guar fix patch posted in discord, I still periodically crash while using carriages to fast travel. The crash logs suggest the guar plugins are relevant. It does not seem to be specific to any city. It is not reproduce-able post-crash; that is, after restarting Skyrim the game works fine. I would say the crash occurs less than 5% of the time the below steps occur, but I have not been keeping track. 

**To Reproduce**

1. Talk to a carriage driver (or ferry person?)
2. Purchase travel to or from a major hold city

**Expected behavior**
Fast travel occurs without crashing

**Screenshots**

N/A

**Modlist version**

2.1

**Did you add any additional mods?**

Only the gamepad setup mods (TUCS, iEquip, Serio), and the fixes posted in discord:
`Lock Overhaul - Thievery.esp`
`mihaildunmermerchants.esp`
`mihailguar.esp`

***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***

**Comment by Althro** [comment]
This should be fixed as of v 2.2.1/2.3
