### ISSUE TITLE
Download Failure on Install: XLODGen.85.7z link broken

### ISSUE THREAD

**Issue by jbpauljr** [Althro/Tinvaak2#20]
While installing for the first time, the link to XLODGen.85.7z is broken and the archive failed to download. After looking this up online, it appears a new version 86.7 was released this week and is now hosted at https://mega.nz/file/8Iog2abQ#0rQzamCU_uv68QpnBjvlR8SSepyek7LM6sow4rQFh_c. 

Details on this forum post:
https://stepmodifications.org/forum/topic/13451-xlodgen-terrain-lod-beta-86-for-fnv-fo3-fo4-fo4vr-tes5-sse-tes5vr-enderal-enderalse/
[Wabbajack.current.log](https://github.com/Althro/Tinvaak2/files/7876078/Wabbajack.current.log)

Broken existing link for reference:
https://mega.nz/file/kNRCHRDY#ONIMDnlxyyBH-QsSUgatbQJWOgGGrr8F8bxWD_-bSGc

Wabbajack log file attached. [Wabbajack.current.log](https://github.com/Althro/Tinvaak2/files/7876078/Wabbajack.current.log)

**Comment by Althro** [comment]
This is not something I have any control over. If you join the discord server for the list, there is a workaround to enable the list to be released.

**Comment by jbpauljr** [comment]
Thanks for the quick help!
