### ISSUE TITLE
[BUG] Crashing frequently when assuming Lich Form

### ISSUE THREAD

**Issue by chilblane** [Althro/Tinvaak2#23]
**Upload your crashlog**

[Crash_2022_1_16_21-57-48.txt](https://github.com/Althro/Tinvaak2/files/7883570/Crash_2022_1_16_21-57-48.txt)
[Crash_2022_1_16_22-11-35.txt](https://github.com/Althro/Tinvaak2/files/7883571/Crash_2022_1_16_22-11-35.txt)
[Crash_2022_1_17_9-26-47.txt](https://github.com/Althro/Tinvaak2/files/7883572/Crash_2022_1_17_9-26-47.txt)
[Crash_2022_1_17_9-29-27.txt](https://github.com/Althro/Tinvaak2/files/7883573/Crash_2022_1_17_9-29-27.txt)

**Required: Modlist.txt**

[modlist.txt](https://github.com/Althro/Tinvaak2/files/7883576/modlist.txt)

**Describe the bug**
Changing into a Lich regularly causes the game to crash to desktop during the transformation animation. May be related to skeletons, Engarde, racials, who knows

**To Reproduce**

1. Unlock Assume Lich Form
2. Cast that power

**Expected behavior**
Not crash

**Screenshots**
N/A

**Modlist version**

2.1

**Did you add any additional mods?**

no

***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***

**Comment by Althro** [comment]
Should be fixed in 2.2
