### ISSUE TITLE
[BUG] OBIS Bandits Werewolf Invisible after transformation

### ISSUE THREAD

**Issue by xNoHudx** [Althro/Tinvaak2#24]
My Modlist txt : 
[modlist.txt](https://github.com/Althro/Tinvaak2/files/7899733/modlist.txt)

Every time you bring an OBIS bandit werewolf down to low health to transform he turns invisible and runs away. Naturally your companions are still aggroed and you can see his red dot on the compass but he can't be locked on. They can still be hit with attacks though. 

Happens every time an OBIS bandit werewolf transforms. I haven't seen the Companions transformation yet, but will update when I have. 

Should be just a normal werewolf transformation and fight. 

I have not modified the list, it was a fresh install about two days ago.

**Comment by Althro** [comment]
Should be fixed in 2.2
