### ISSUE TITLE
[BUG] Anvil texture mapping error

### ISSUE THREAD

**Issue by jason1080108** [Althro/Tinvaak2#25]
**Upload your crashlog**

If you've crashed, upload your crashlog from `Overwrite\NetScriptFramework`. Reports of crashes that do not include a crashlog will be **ignored and closed.**

**Required: Modlist.txt**

You must also include your modlist.txt from `F:\Tinvaak\profiles\Tinvaak`

**Describe the bug**
A clear and concise description of what the bug is. Failure to do this will result in the report being **closed and ignored.**
All anvils in-game have a distorted, unaligned texture.
**To Reproduce**

1. Go to any anvil/forge
2. Look at the anvil

**Expected behavior**
Normal texture
**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.
![image](https://user-images.githubusercontent.com/98140055/150462522-dd98f8d0-6774-4d6a-9e04-ec7d98628152.png)

**Modlist version**
Unsure
**Did you add any additional mods?**
Yes I did, but a moderator in the discord said this is a known issue, and the problem was there before I added anything.
***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***

**Comment by Althro** [comment]
Should be fixed in 2.2
