### ISSUE TITLE
[BUG] "Frequent Crashing While Traveling Through Whiterun Hold"

### ISSUE THREAD

**Issue by xNoHudx** [Althro/Tinvaak2#26]
1-26-2022 9:33 Fighting Random Spriggan Encounter on Whiterun Road near Moss Mother Cavern
[Crash_2022_1_24_20-6-12.txt](https://github.com/Althro/Tinvaak2/files/7943389/Crash_2022_1_24_20-6-12.txt)

[modlist.txt](https://github.com/Althro/Tinvaak2/files/7943399/modlist.txt)

Frequent Crashing While Traveling through Whiterun Hold

Consistent crash after travelling about 45 minutes in Whiterun Hold. You can play for hours everywhere else with seemingly no issue. Will continue to update with crashlogs with timestamps as they happen. 

Expectations would naturally be just more stability in that area.

Screenshots not applicable

Tinvaak V2.1

Vanilla Tinvaak install.

**Comment by Althro** [comment]
Should be fixed in 2.2
