### ISSUE TITLE
[BUG] "Vancian Slots Used by Scrolls"

### ISSUE THREAD

**Issue by Beastlicious** [Althro/Tinvaak2#28]
**Upload your crashlog**

If you've crashed, upload your crashlog from `Overwrite\NetScriptFramework`. Reports of crashes that do not include a crashlog will be **ignored and closed.**

**Required: Modlist.txt**

You must also include your modlist.txt from `F:\Tinvaak\profiles\Tinvaak`

**Describe the bug**
A clear and concise description of what the bug is. Failure to do this will result in the report being **closed and ignored.**

**To Reproduce**

2. Do '...'

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

**Modlist version**

**Did you add any additional mods?**

***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***

**Comment by Althro** [comment]
Way more information is required than just that.

**Comment by Beastlicious** [comment]
[modlist.txt](https://github.com/Althro/Tinvaak2/files/8052042/modlist.txt)

Using scrolls and SA Alchemy bombs deducts the slots used to cast spells when the Vancian perk from the Alteration tree is taken. 

To reproduce, first have the requisite perk. Find out how many slots you have to start with by checking in your active effects list. Use a scroll, trap or bomb from the scrolls section. Then check the "Vancian Magic" buff to determine how many you have left.

Expected Behavior: Scrolls, powers and the like not reducing the amount of Vancian slots.

Modlist Version: 2.1

Additional mods: Those taken from the known bugs section.

**Comment by Beastlicious** [comment]
> [modlist.txt](https://github.com/Althro/Tinvaak2/files/8052042/modlist.txt)
> 
> Using scrolls and SA Alchemy bombs deducts the slots used to cast spells when the Vancian perk from the Alteration tree is taken.
> 
> To reproduce, first have the requisite perk. Find out how many slots you have to start with by checking in your active effects list. Use a scroll, trap or bomb from the scrolls section. Then check the "Vancian Magic" buff to determine how many you have left.
> 
> Expected Behavior: Scrolls, powers and the like not reducing the amount of Vancian slots.
> 
> Modlist Version: 2.1
> 
> Additional mods: Those taken from the known bugs section.

First time using Github.

**Comment by Althro** [comment]
Thank you. Can you please provide your saves so that we can investigate? .ess and skse cosave file required.

**Comment by Beastlicious** [comment]
I adjusted several MCMs to suit my tastes (Like turning off True Directional Movement or adjusting Engarde). Would that mess up your own settings?

**Comment by Althro** [comment]
If you could list the one's you have changed that would be helpful.
