### ISSUE TITLE
[BUG] "Details"

### ISSUE THREAD

**Issue by WillLaDrill** [Althro/Tinvaak2#29]
**Upload your crashlog**
[Crash_2022_2_12_10-15-55.txt](https://github.com/Althro/Tinvaak2/files/8053789/Crash_2022_2_12_10-15-55.txt)

If you've crashed, upload your crashlog from `Overwrite\NetScriptFramework`. Reports of crashes that do not include a crashlog will be **ignored and closed.**

**Required: Modlist.txt**
[modlist.txt](https://github.com/Althro/Tinvaak2/files/8053821/modlist.txt)

You must also include your modlist.txt from `F:\Tinvaak\profiles\Tinvaak`

**Describe the bug**
A clear and concise description of what the bug is. Failure to do this will result in the report being **closed and ignored.**
I just start the game, select a save and it crash right after.

**To Reproduce**

1. Go to '...'Open up the game
2. Do '...'Select a save and crash

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am [](I](https://www.nexusmods.com/skyrimspecialedition/mods/30907)) mod.

**Modlist version**

**Did you add any additional mods?**
I added Serana Dialogue Add-on but even without it doesn't work

***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***

**Comment by Althro** [comment]
**A lot more information si required than that.** You have also modified the list and thus void support until you remove it.
