### ISSUE TITLE
[BUG] Sojourn Over Signposts mod has ongoing issue which causes fast travel via signposts to become impossible

### ISSUE THREAD

**Issue by jbpauljr** [Althro/Tinvaak2#33]
The bugs page for the Sojourn Over Signposts mod (https://www.nexusmods.com/skyrimspecialedition/mods/51567?tab=bugs) lists a bug which prevents signposts from being used after several hours in a run. The comments history shows that this error has continued after the latest update. I encountered this in my playthrough and was forced to deactivate the mod and start a new character in order to enable fast travel. It may be advisable to remove this mod in order to prevent others from encountering this issue. Thanks for the great modlist!
*List is not modified*
[modlist.txt](https://github.com/Althro/Tinvaak2/files/8316786/modlist.txt)

**Comment by Althro** [comment]
This is a known issue and there is workaround posted in the Animonculory discord server on how to get around it. You do raise a good point about removal though. I will bear this in mind.

**Comment by jbpauljr** [comment]
Thanks for the quick response! Really respect all the work you put into this modlist.

**Comment by Althro** [comment]
Fixed in V2.3 (coming soon)
