### ISSUE TITLE
Go into slow motion when pressing LMB to attack

### ISSUE THREAD

**Issue by Wotchim** [Althro/Tinvaak2#34]
**Upload your crashlog**

If you've crashed, upload your crashlog from `Overwrite\NetScriptFramework`. Reports of crashes that do not include a crashlog will be **ignored and closed.**

**Required: Modlist.txt**

You must also include your modlist.txt from `F:\Tinvaak\profiles\Tinvaak`

**Describe the bug**
Pressing left mouse button to attack makes the character go into slow motion.

**Expected behavior**
Not to go into slow motion ;)

**Modlist version**
2.2.0

**Did you add any additional mods?**
No

***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***
No modifications to the list

**Comment by Althro** [comment]
Fixed in V2.3 (coming soon)
