### ISSUE TITLE
[BUG] Floating Table in Falkreath

### ISSUE THREAD

**Issue by Zyquis** [Althro/Tinvaak2#35]
**Upload your crashlog**

N/a

**Required: Modlist.txt**

[modlist.txt](https://github.com/Althro/Tinvaak2/files/8354851/modlist.txt)

**Describe the bug**

The cat donation table in Falkreath floats above the ground.

**To Reproduce**

1. Go to Falkreath
2. Look beneath the Dead Man's Drink and you will find the table.

**Expected behavior**
For the table to not float.

**Screenshots**
![enb2022_3_24_18_35_09](https://user-images.githubusercontent.com/83829459/160231898-68af1245-5fd0-41c3-905d-bb91398a642a.jpg)

**Modlist version**

Appears in both Khajit speak and non KSP versions of the list as I tested both.

**Did you add any additional mods?**

No.

**Comment by Althro** [comment]
Fixed in 2.3 (coming soon)
