### ISSUE TITLE
[BUG] Unable to cast spell with left hand when wielding weapon in right.

### ISSUE THREAD

**Issue by oswaltdw** [Althro/Tinvaak2#36]
**Upload your crashlog**
N/A

**Required: Modlist.txt**

[modlist.txt](https://github.com/Althro/Tinvaak2/files/8359442/modlist.txt)

**Describe the bug**
Couldn't cast spell in left hand with weapon in right.

**To Reproduce**

1. One handed weapon or hand2hand "weapon" in right hand, spell in left hand.
2. Try to cast spell in left hand

**Expected behavior**
Should be able to cast left hand spells with engarde gone

**Screenshots**

![The Elder Scrolls V  Skyrim Special Edition 2022 03 27 - 23 18 55 02_Moment(2)](https://user-images.githubusercontent.com/58856785/160321982-75b97e81-0a0d-42a9-8024-7903752ffbec.jpg)
![The Elder Scrolls V  Skyrim Special Edition 2022 03 27 - 23 18 55 02_Moment](https://user-images.githubusercontent.com/58856785/160321986-11b31c9f-1ef6-4702-9c3e-f626e8232ffa.jpg)

**Modlist version**
2.2.0

**Did you add any additional mods?**

I used a different bodyslide preset already in the list and PiChoENB. Nothing else was changed.

**Comment by Althro** [comment]
We are looking into this. It should be fixed in version 2.3 (coming soon).

**Comment by Althro** [comment]
I can repeat this issue, however due to intricacies with SkySa we're not able to fullly fix this sadly.
