### ISSUE TITLE
[BUG] Purple hair mesh on Dunmer Pedlar

### ISSUE THREAD

**Issue by beangusu** [Althro/Tinvaak2#39]
**Upload your crashlog**
N/A

**Required: Modlist.txt**
[modlist.txt](https://github.com/Althro/Tinvaak2/files/8456152/modlist.txt)

**Describe the bug**
Dunmer Pedlar has missing hair textures; purple hair mesh

**To Reproduce**

1. Go to Windhelm, in front of the main bridge
2. Look for Dunmer Peddlar
3. Profit

**Expected behavior**
For the Dunmer Pedlar to not have purple hair

**Screenshots**
![The_Elder_Scrolls_V_Skyrim_Special_Edition_Screenshot_2022 04 08_-_05 04 00 93](https://user-images.githubusercontent.com/103297439/162554926-8ca28290-aa6d-4cdf-83f8-8be95731199a.png)

**Modlist version**
Tinvaak V2.3.1

**Did you add any additional mods?**
No

**Comment by Althro** [comment]
Should be fixed in V2.4
