### ISSUE TITLE
[BUG] "Stop installing"

### ISSUE THREAD

**Issue by BlessedName** [Althro/Tinvaak2#4]
A log attached.  **Please any solution for me
[Wabbajack 2021-10-10 02_24_21.log](https://github.com/Althro/Tinvaak2/files/7438949/Wabbajack.2021-10-10.02_24_21.log)
[Wabbajack 2021-10-10 02_29_17.log](https://github.com/Althro/Tinvaak2/files/7438952/Wabbajack.2021-10-10.02_29_17.log)
**

**Comment by BlessedName** [comment]
[Wabbajack 2021-10-10 02_29_17.log](https://github.com/Althro/Tinvaak2/files/7445622/Wabbajack.2021-10-10.02_29_17.log)

**Comment by Althro** [comment]
I advise you join the Wabbajack discord and post your log in there as I am not familar with that error. The only thing I can think what might be causing the error is because you have non english characters in your folder structure.

**Comment by BlessedName** [comment]
Thank you for email. It was first time installation in a empty folder and none of English charaters. Windows용 메일에서 발송된 메일입니다. 보낸 사람: Al보낸 날짜: 2021년 10월 31일 일요일 오전 8:08받는 사람: Althro/Tinvaak2참조: BlessedName; Author제목: Re: [Althro/Tinvaak2] [BUG] "Stop installing" (Issue #4) I advise you join the Wabbajack discord and post your log in there as I am not familar with that error. The only thing I can think what might be causing the error is because you have non english characters in your folder structure.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
