### ISSUE TITLE
[BUG] "Double bed in Helgen from Alternate Perspective will not change ownership, can't start Main Quest"

### ISSUE THREAD

**Issue by profundity77** [Althro/Tinvaak2#41]
**Upload your crashlog**
No crash

**Required: Modlist.txt**
[modlist.txt](https://github.com/Althro/Tinvaak2/files/8476630/modlist.txt)

**Describe the bug**
After speaking with Matlara to start the intro in Helgen, the double bed does not change ownership, so I cannot start the main quest.

**To Reproduce**

1. Go to Helgen
2. Speak to Matlara to start the intro quest
3. Attempt to sleep in the double bed

**Expected behavior**
I should be able to sleep in the double bed after asking Matlara to extend my stay. The intro should then take place.

**Screenshots**
![enb2022_4_12_14_05_01](https://user-images.githubusercontent.com/96799215/163055959-f4c2fec3-da70-4358-abdb-60bf37881cb4.png)

**Modlist version**
V2.3.1

**Did you add any additional mods?**
No

***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***
I disabled the ENB, but it is otherwise unmodified

**Comment by Althro** [comment]
Fixed in Version 2.4
