### ISSUE TITLE
[BUG] "All attacks in first person are slow motion"

### ISSUE THREAD

**Issue by Denthamos** [Althro/Tinvaak2#42]
**Upload your crashlog**

No crashlog present

**Required: Modlist.txt**

[modlist.txt](https://github.com/Althro/Tinvaak2/files/8509502/modlist.txt)

**Describe the bug**
Any melee attack in first person randomly will perform in slow motion.  Ranged attacks with crossbows/bows will result in the projectile leaving the weapon in slow motion.  Projectile spells will also travel in slow motion.

**To Reproduce**
Download recent version of Tinvaak from wabbajack, follow instructions, play game.  Really did not do anything out of the ordinary.

**Expected behavior**
For all attacks in first person to not be in slow motion as if the cinematic kill camera is constantly active.

**Screenshots**
No screenshots -needs active video

**Modlist version**
Where do you find modlist version?  One I downloaded is as of 4/17/22

**Did you add any additional mods?**
No
***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***

**Comment by Althro** [comment]
Please use the MCM menu from [Weapon Speed Mult Fix](https://www.nexusmods.com/skyrimspecialedition/mods/45502) to apply the fix if it has not applied.
