### ISSUE TITLE
TLods.7z Corrupted?

### ISSUE THREAD

**Issue by sp3tral** [Althro/Tinvaak2#43]
![image_2022-04-23_081103789](https://user-images.githubusercontent.com/43689512/164893924-4c0777eb-2393-4f7d-ad60-fe0f02c0e2bc.png)
[Wabbajack 2022-04-22 23_14_04.log](https://github.com/Althro/Tinvaak2/files/8546899/Wabbajack.2022-04-22.23_14_04.log)

Have not modded the list

Not sure if its my end, Tinvaaks or Wabbajack, but whenever Wabbajack tries to download Tlods.7z the file is corrupted I added a screen shot and logs but it prevents installation

**Comment by Althro** [comment]
Please use this link to manually download the file: https://build.wabbajack.org/authored_files/direct_link/TLods.7z_ec02b7e9-5ed0-48a3-a42c-1cb32b3364db
