### ISSUE TITLE
[BUG] Texture error with ClefJ's Dawnguard

### ISSUE THREAD

**Issue by Ajexais** [Althro/Tinvaak2#44]
**Describe the bug**
Tower bug with ClefJ's dawnguard, it has since been updated and acknowledged by the mod author

(https://www.nexusmods.com/skyrimspecialedition/mods/33044?tab=files)

**To Reproduce**

1. Go to 'ford dawnguard'
2. Do 'goto entrance'

**Expected behavior**
tower wrong

**Tinvaak 2 Downloaded 18April2022**

**Did you add any additional mods?**
Enb only

***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***

**Comment by Althro** [comment]
Thanks for the report, this should be fixed in Version 2.4
