### ISSUE TITLE
Can't get the mod to launch via the MO2 

### ISSUE THREAD

**Issue by RomboGold** [Althro/Tinvaak2#5]
I've done everything right (to my knowledge of course). I've got a clean Skyrim SE (it's also downloaded outside of the program files), followed all the steps for post-installation for the mod pack. When I click "run" it loads and then doesn't do anything. If you think you know a solution, please let me know. 

Thank you so much for reading. I adore the first Tinvaak and I am very excited for the second!!

**Comment by RomboGold** [comment]
Update. The game is now launching.... but It isn't working as intended. When I go to make a new game it crashes on the loading screen. plus the main menu is like the default Skyrim with a purple 'gellow' Skyrim logo.... (yes it looks as it sounds)

**Comment by Gamerbomb** [comment]
I have same problem. I did everything what i was supposed to do and it didnt launch :/

**Comment by EmpressLexi** [comment]
Same problem here.

**Comment by Pearldrummer0147** [comment]
I was having the same problem as well.  It would act like it was going to start but then not.  I had to download the latest version of Microsoft .Net Runtime v5.  The download is right at the beginning of the post installation instructions.

[https://dotnet.microsoft.com/download/dotnet/5.0/runtime](url)

**Comment by RomboGold** [comment]
> 
> 
> I was having the same problem as well. It would act like it was going to start but then not. I had to download the latest version of Microsoft .Net Runtime v5. The [download](https://dotnet.microsoft.com/download/dotnet/5.0/runtime) is right at the beginning of the post installation instructions.

I thought this was the solution, I had not done this. Just downloaded it and it's the same... I thought for sure this would solve it. sadly no...

**Comment by Althro** [comment]
This sounds like the install has not completed. Please ensure that wabbajack has finished the installation and did not say "encountered error". Please also ensure you have .net v5, have no antivirus other than windows defender and have set exclusions in the areas where you are running the list.

**Comment by Althro** [comment]
Also, if you have used a list that utilises the "Game Registry fix" plugin for ModOrganizer, you will need to totally uninstall Skyrim SE and then reinstall it and run it once to reset the registry path.

**Comment by RomboGold** [comment]
> 
> 
> This sounds like the install has not completed. Please ensure that wabbajack has finished the installation and did not say "encountered error". Please also ensure you have .net v5, have no antivirus other than windows defender and have set exclusions in the areas where you are running the list.

It's finally working. the installation wasn't complete. Very weird. I am very sure that it was installed correctly... nevertheless I did the install again, and now it's working !!! Thank you so much for the help and the mod pack!!!
