### ISSUE TITLE
[BUG] "Details"

### ISSUE THREAD

**Issue by Bandiusha** [Althro/Tinvaak2#6]
**Upload your crashlog**

[Wabbajack.current.log](https://github.com/Althro/Tinvaak2/files/7478003/Wabbajack.current.log)

**Required: Modlist.txt**

ONE FILE FAILED TO DOWNLOAD MULTIPLE TIMES IN WABBAJACK!

**Describe the bug**
ONE FILE FAILED TO DOWNLOAD MULTIPLE TIMES IN WABBAJACK!
https://authored-files.wabbajack.org/T2LandscapeResources.7z_8068694a-563d-4234-93fc-88a215cd6603
Not able to manually download it either!

**To Reproduce**
Re-upload the file please! T2LandscapeResources.7z

**Expected behavior**
Re-upload the file please! T2LandscapeResources.7z

**Screenshots**
![Screenshot 2021-11-04 213820](https://user-images.githubusercontent.com/93736660/140408294-6e788e97-5ffd-42c3-8932-4d65020fcb03.png)

**Modlist version**

Latest release as of 2021/01/03

**Did you add any additional mods?**

No, clean install for the first time in years.

***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***

**Comment by Althro** [comment]
Please join the wabbajack discord server where a mirror to the file can be found.

**Comment by Bandiusha** [comment]
Hey @Althro  , thank you for your reply. Can't find the download link anywhere on discord. Only suggestion to use the workaround in settings and the network workaround was always on for me cause I watched some tutorial on youtube and it recommended to have it on.

Tried using the search as well, can't find any alternative links to the file.

**Comment by Althro** [comment]
It is linked in the support channel. Please check the pins.
